url: https://joyrapture.github.io/
baseurl: /joyRapture.github.io

# Site settings
title: SOHEE LEE
email: 715sohappy@gmail.com
description: "will be a great developer."


# Team names, titles and social links
people:
- name: SOHEE LEE
  pic: 1
  position: Web Programmer
  social:
    - title: instagram
      url: #
    - title: linkedin
      url: #
    - title: github
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://twitter.com/jekyllrb
  - title: linkedin
    url:
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 경기도 포천시
  - line: 소흘읍 봉솔로 9, 11180

# Build settings
markdown: kramdown
permalink: pretty
